[package]
name = "protocol"
version = "0.1.0"
authors = ["louga31 <louga31@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
