name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.5
      with:
        rust-version: nightly
        # The components to install
        components: rust-src
        # The targets to install
        targets: "x86_64-unknown-uefi x86_64-pc-windows-msvc"
    
    - name: rust-cargo-make
      uses: davidB/rust-cargo-make@v1.6.0
      
    - name: Build
      run: cargo make
